Module3 task1
htmlacademy-javascript/1343133-keksobooking-22 pull request #3
Opened 2021-02-18 14:32 UTC by igor26111963

2021-02-18 17:10 UTC, igor26111963 commented
ДЗ - 3

2021-02-19 22:45 UTC, ant1quar requested changes

2021-02-19 22:45 UTC, ant1quar commented on js/main.js
> +let randomType = Math.floor(Math.random() * type.length);
Все подобные конструкции нужно заменить на `random(0, ARRAY.length)` прямо в функции `generateCard` не нужно для этого заводить отдельную переменную

2021-02-19 22:45 UTC, ant1quar commented on js/main.js
> +let featuresList = ['wifi', 'dishwasher', 'parking', 'washer', 'elevator', 'conditioner',];
Такие переменные стоит объявить через `const`, они не меняются вов время выполнения программы

2021-02-19 22:45 UTC, ant1quar commented on js/main.js
> +};
Вот тут прям отлично! 👍 смысл понят верно

2021-02-19 22:45 UTC, ant1quar commented on js/main.js
> +};
Стоит обернуть в функицю `getRandomPhotos()` которая вернет этот массив. ее параметром будет длина `randomPhotosLength`

2021-02-20 10:00 UTC, igor26111963 commented
Привет! Ваня, проясни:
+const type = ['palace', 'flat', 'house', 'bungalow',];

+let randomType = Math.floor(Math.random() * type.length);

Все подобные конструкции нужно заменить на random(0, ARRAY.length) прямо в функции generateCard не нужно для этого заводить отдельную переменную. 
В generateCard  вывожу 
type :   ` ${ random ( 0 ,  Array . length ) }  
получаю 
*  offer :   { title :   "Сдаётся уютное жильё" ,   address :   "35.69404 , 139.87018 " ,   price :   "617 " ,   type :   "0 " ,   rooms :   "4 " , … }.
*  У меня телеграмм глюканул на ноуте. 
>Суббота, 20 февраля 2021, 1:45 +03:00 от ant1quar <notifications@github.com>:
> 
> 
>@ant1quar requested changes on this pull request.
>----------------------------------------------------------------------
>In  js/main.js :
>> @@ -41,17 +41,8 @@ let price = () => random(100, 1000);
>
> 
>
> // type
>
> 
>
>-let type = [
>
>-  'palace',
>
>-  'flat',
>
>-  'house',
>
>-  'bungalow',
>
>-];
>
>-let typeIndex = () => {
>
>-  const randomTypeIndex = _.random(0, type.length - 1);
>
>-  return type[randomTypeIndex]
>
>-}
>
>-
>
>+const type = ['palace', 'flat', 'house', 'bungalow',];
>
>+let randomType = Math.floor(Math.random() * type.length);
>
>
>Все подобные конструкции нужно заменить на random(0, ARRAY.length) прямо в функции generateCard не нужно для этого заводить отдельную переменную
>----------------------------------------------------------------------
>In  js/main.js :
>>  
>
> // features
>
> 
>
>+let randomfeaturesLength = random(0, 5);
>
>+let featuresCard = [];
>
>+let featuresList = ['wifi', 'dishwasher', 'parking', 'washer', 'elevator', 'conditioner',];
>
>
>Такие переменные стоит объявить через const, они не меняются вов время выполнения программы
>----------------------------------------------------------------------
>In  js/main.js :
>> +for (let option = 0; option <= randomfeaturesLength; option++) {
>
>+  featuresCard.push(featuresList[option])
>
>+};
>
>
>Вот тут прям отлично! 👍 смысл понят верно
>----------------------------------------------------------------------
>In  js/main.js :
>> +let randomNewPhotos = [];
>
>+let randomPhotos = ['http://o0.github.io/assets/images/tokyo/hotel1.jpg', 'http://o0.github.io/assets/images/tokyo/hotel2.jpg', 'http://o0.github.io/assets/images/tokyo/hotel3.jpg'];
>
>+for (let photo = 0; photo <= randomPhotosLength; photo++) {
>
>+  randomNewPhotos.push(randomPhotos[photo])
>
>+};
>
>
>Стоит обернуть в функицю getRandomPhotos() которая вернет этот массив. ее параметром будет длина randomPhotosLength
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
С уважением,
игорь полторак
poltorak63@mail.ru
 

2021-02-20 14:50 UTC, igor26111963 commented
Правки

2021-02-21 17:22 UTC, merged